export const routes = {
  products: "/products",
  categories: "/categories",
  categoryProducts: (id: string) => `/categories/${encodeURIComponent(id)}/products`,
  popularProducts: "/products/popular",
  discountedProducts: "/products/discounted",
  newArrivals: "/products/new-arrivals",
  mostSoldProducts: "/products/most-sold",
  bestSellingProducts: "/products/best-selling",
  productAvailability: (id: string) => `/products/${encodeURIComponent(id)}/availability`,
  bookings: "/bookings",
  cart: "/cart",
  cartUpdate: "/cart/update",
  cartComplete: "/cart/complete",
  cartClear: "/cart/clear",
  orders: "/orders",
  orderTracking: "/orders/track",
  order: (id: string) => `/orders/${encodeURIComponent(id)}`,
  paymentConfig: "/payments/config",
  paymentInitialize: "/payments/initialize",
  paymentVerify: "/payments/verify",
  configuration: "/config",
  storeInfo: "/store-info",
  agentChat: "/agent/chat",
} as const;
