import Link from "next/link";

export const dynamic = "force-dynamic";

export const metadata = { title: "Terms & Conditions — Alicia Phone Place" };

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#f7f8f5] px-5 py-12">
      <div className="mx-auto max-w-3xl mb-6">
        <Link href="/" className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#166534] hover:text-[#14532d]">← Back to home</Link>
      </div>
      <article className="mx-auto max-w-3xl rounded-2xl border border-[#e2ece4] bg-white p-6 md:p-10">
        <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#166534]">Legal</p>
        <h1 className="mt-2 font-display text-3xl font-black tracking-tight text-[#0f172a] md:text-4xl">Terms &amp; Conditions</h1>
        <p className="mt-2 text-sm text-[#64748b]">Last updated: July 2026</p>

        <div className="mt-8 space-y-6 text-sm leading-7 text-[#0f172a]/80">
          <section>
            <h2 className="font-bold text-[#0f172a]">1. Acceptance of Terms</h2>
            <p className="mt-2">By accessing or purchasing from the Alicia Phone Place website, you agree to be bound by these Terms &amp; Conditions. If you do not agree, please do not use our website or services.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">2. Products &amp; Pricing</h2>
            <p className="mt-2">All products are subject to availability. We reserve the right to modify prices, descriptions, and availability without notice. Every effort is made to display accurate product images and specifications, but actual products may vary slightly.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">3. Orders</h2>
            <p className="mt-2">When you place an order, you will receive an order confirmation. We reserve the right to refuse or cancel any order at our discretion, including due to product unavailability, pricing errors, or suspected fraudulent activity.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">4. Payment</h2>
            <p className="mt-2">Payments are processed through secure third-party payment gateways. We accept mobile money and card payments. Your order will only be confirmed after successful payment verification.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">5. Delivery</h2>
            <p className="mt-2">We offer free delivery around Juja town. Delivery to other areas may incur additional charges. Estimated delivery times are provided at checkout but are not guaranteed. We are not liable for delays caused by third-party delivery providers.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">6. Returns &amp; Refunds</h2>
            <p className="mt-2">Products may be returned within 7 days of delivery if they are defective, damaged, or significantly different from what was ordered. Items must be in their original packaging with all accessories included. Refunds are processed to the original payment method within 5–10 business days.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">7. Warranty</h2>
            <p className="mt-2">All genuine products carry the manufacturer&apos;s warranty. Warranty claims must be directed to the manufacturer or our store. We will assist you in processing warranty claims where possible.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">8. AI Assistant</h2>
            <p className="mt-2">Our AI shopping assistant provides general product information and recommendations. The assistant&apos;s responses are generated by AI and may not always be accurate. For specific product details, pricing, or stock availability, please contact our customer care team.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">9. Limitation of Liability</h2>
            <p className="mt-2">Alicia Phone Place shall not be liable for any indirect, incidental, or consequential damages arising from the use of our website or products. Our total liability shall not exceed the value of your purchase.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">10. Changes to Terms</h2>
            <p className="mt-2">We may update these Terms &amp; Conditions at any time. Continued use of our website after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="font-bold text-[#0f172a]">11. Contact Us</h2>
            <p className="mt-2">If you have any questions about these Terms &amp; Conditions, please contact us:</p>
            <ul className="mt-2 list-disc pl-5">
              <li>Phone / WhatsApp: +254 724 126 009</li>
              <li>Email: aliciaphoneplaceke@gmail.com</li>
              <li>Location: Juja town, Kenya</li>
            </ul>
          </section>
        </div>
      </article>
    </main>
  );
}
