import Link from "next/link";
import type { Product } from "@/lib/api/types";

export function FeaturedProducts({ products, currency }: { products: Product[]; currency: string }) {
  const featured = products.slice(0, 3);
  if (!featured.length) return null;
  const money = (value: number | string | null | undefined) => new Intl.NumberFormat("en-KE", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(value || 0));
  return <section className="mx-auto max-w-7xl px-5 py-6"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#18864e]">Chosen for you</p><h2 className="mt-1 font-display text-2xl font-black tracking-[-0.05em]">Featured products</h2></div><Link href="/shop" className="text-xs font-bold text-[#147243] hover:underline">Shop everything</Link></div><div className="mt-5 grid gap-4 md:grid-cols-3">{featured.map((product, index) => <Link key={product.id} href={`/products/${product.id}`} className="group relative min-h-52 overflow-hidden rounded-3xl bg-[#e7f5e8] p-6 transition hover:-translate-y-1 hover:shadow-lg"><div className={`absolute -right-16 -bottom-16 h-56 w-56 rounded-full ${index === 1 ? "bg-[#d7e9ff]" : index === 2 ? "bg-[#f8e7d8]" : "bg-[#bfe9c7]"}`}/><div className="relative flex h-full flex-col justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-[#147243]">Editor&apos;s pick</p><h3 className="mt-3 max-w-[14rem] font-display text-xl font-black leading-tight text-[#173d26]">{product.name}</h3></div><div><p className="font-display text-lg font-black text-[#147243]">{money(product.sales_price ?? product.price)}</p><span className="mt-2 inline-block text-[10px] font-black uppercase tracking-wider text-[#245735]">View product →</span></div></div>{product.images?.[0] && <img src={product.images[0]} alt="" onError={(e) => { (e.currentTarget as HTMLImageElement).src = "/Phoneplacelg.png"; }} className="absolute bottom-3 right-3 h-32 w-32 object-contain mix-blend-multiply transition duration-500 group-hover:scale-110"/>}</Link>)}</div></section>;
}
